#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Writes HearOn Link's vector drawables (UI glyphs, listening modes, launcher and splash icons).

The glyphs are simple 24-unit stroke drawings, the same ones as on the design canvas. Circles become
two arcs because Android vector paths have no <circle>. Run: python3 tools/icons.py
"""
import math
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "app/src/main/res/drawable"


def circle(cx, cy, r):
    return f"M{cx - r},{cy}a{r},{r} 0 1,0 {2 * r},0a{r},{r} 0 1,0 {-2 * r},0z"


# name: list of (kind, path) where kind is "s" (stroke) or "f" (fill)
GLYPHS = {
    "down": [("s", "M7,10l5,5 5,-5")],
    "right": [("s", "M9,6l6,6 -6,6")],
    "back": [("s", "M19,12H5"), ("s", "M11,6l-6,6 6,6")],
    "more": [("f", circle(12, 5, 1.6) + circle(12, 12, 1.6) + circle(12, 19, 1.6))],
    "tune": [("s", "M4,7h9M18,7h2M4,17h3M12,17h8"), ("s", circle(15.5, 7, 2.3)), ("s", circle(9.5, 17, 2.3))],
    "bolt": [("f", "M13,3L6,13h5l-1,8 7,-10h-5z")],
    "head": [("s", circle(12, 8.5, 4)), ("s", "M5,20c1.4,-3.6 4,-5.2 7,-5.2s5.6,1.6 7,5.2")],
    "ear": [("s", "M7.5,9.5a4.5,4.5 0 0,1 9,0c0,3.2 -3.4,4 -3.4,7a2.6,2.6 0 0,1 -5.1,0.6"), ("s", "M10.5,9.5a1.5,1.5 0 0,1 3,0")],
    "hold": [("s", "M12,3a3,3 0 0,1 3,3v6a3,3 0 0,1 -6,0v-6a3,3 0 0,1 3,-3z"), ("s", "M12,15v6M8,19h8")],
    "info": [("s", circle(12, 12, 9)), ("s", "M12,11v5.5"), ("f", circle(12, 7.8, 1.1))],
    "check": [("s", "M5,12.5l4.5,4.5L19,7")],
    "close": [("s", "M7,7l10,10M17,7L7,17")],
    "play": [("f", "M8,5.5v13l10.5,-6.5z")],
    "bt": [("s", "M7,7.5l10,9 -5,4.5V3l5,4.5 -10,9")],
    "edit": [("s", "M4,20h4L19,9l-4,-4L4,16z")],
    "open": [("s", "M14,4h6v6"), ("s", "M20,4l-9,9"), ("s", "M18,14v5a1,1 0 0,1 -1,1H5a1,1 0 0,1 -1,-1V7a1,1 0 0,1 1,-1h5")],
    "volume": [("s", "M4,9.5v5h3.5L12,18V6L7.5,9.5z"), ("s", "M15.5,9a4,4 0 0,1 0,6")],
    "bell": [("s", "M6,16V11a6,6 0 0,1 12,0v5l1.5,2h-15z"), ("s", "M10,20.5a2,2 0 0,0 4,0")],
    "tiles": [("s", "M6,4h3a2,2 0 0,1 2,2v3a2,2 0 0,1 -2,2h-3a2,2 0 0,1 -2,-2v-3a2,2 0 0,1 2,-2zM15,4h3a2,2 0 0,1 2,2v3a2,2 0 0,1 -2,2h-3a2,2 0 0,1 -2,-2v-3a2,2 0 0,1 2,-2zM6,13h3a2,2 0 0,1 2,2v3a2,2 0 0,1 -2,2h-3a2,2 0 0,1 -2,-2v-3a2,2 0 0,1 2,-2zM15,13h3a2,2 0 0,1 2,2v3a2,2 0 0,1 -2,2h-3a2,2 0 0,1 -2,-2v-3a2,2 0 0,1 2,-2z")],
    "widget": [("s", "M5,6h14a2,2 0 0,1 2,2v8a2,2 0 0,1 -2,2H5a2,2 0 0,1 -2,-2V8a2,2 0 0,1 2,-2z"), ("s", "M7,12h5")],
    "palette": [("s", circle(12, 12, 8.5)), ("f", circle(8.5, 10, 1.3) + circle(12, 7.5, 1.3) + circle(15.5, 10, 1.3))],
    # listening modes: one "sound field" family
    "mode_off": [("s", circle(12, 12, 7.5)), ("s", "M5.5,18.5l13,-13")],
    "mode_tr": [("f", circle(12, 12, 2.6) + "".join(circle(round(12 + 8 * math.cos(a), 2), round(12 + 8 * math.sin(a), 2), 1.15) for a in [i * math.pi / 4 for i in range(8)]))],
    "mode_ad": [("s", circle(12, 12, 8)), ("f", "M12,4a8,8 0 0,1 0,16z")],
    "mode_nc": [("f", circle(12, 12, 4)), ("s", circle(12, 12, 8))],
}


def vector(paths, size=24, stroke=2.0):
    body = []
    for kind, d in paths:
        if kind == "s":
            body.append(f'    <path android:pathData="{d}" android:strokeColor="#FF000000" android:strokeWidth="{stroke}" '
                        f'android:strokeLineCap="round" android:strokeLineJoin="round" android:fillColor="#00000000"/>')
        else:
            body.append(f'    <path android:pathData="{d}" android:fillColor="#FF000000"/>')
    return (f'<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by tools/icons.py -->\n'
            f'<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="{size}dp" android:height="{size}dp" '
            f'android:viewportWidth="24" android:viewportHeight="24" android:tint="?android:attr/colorControlNormal">\n'
            + "\n".join(body) + "\n</vector>\n")


# The link mark: two capsules interlocked at -38°, each with a small "bud" dot. 108-unit adaptive canvas.
def mark(color, stroke=9.0):
    t = 'android:rotation="-38" android:pivotX="54" android:pivotY="54"'
    # Capsules spanning x 20..66 and 42..88, 28 tall (as on the design canvas).
    caps = ('M34,40h18a14,14 0 0,1 0,28h-18a14,14 0 0,1 0,-28z'
            'M56,40h18a14,14 0 0,1 0,28h-18a14,14 0 0,1 0,-28z')
    dots = circle(34, 54, 5.5) + circle(74, 54, 5.5)
    return (f'  <group {t}>\n'
            f'    <path android:pathData="{caps}" android:strokeColor="{color}" android:strokeWidth="{stroke}" android:strokeLineCap="round" android:fillColor="#00000000"/>\n'
            f'    <path android:pathData="{dots}" android:fillColor="{color}"/>\n  </group>\n')


def adaptive_layer(content, scale=1.0):
    g = f'<group android:scaleX="{scale}" android:scaleY="{scale}" android:pivotX="54" android:pivotY="54">\n{content}</group>\n' if scale != 1.0 else content
    return ('<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by tools/icons.py -->\n'
            '<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="108dp" android:height="108dp" '
            'android:viewportWidth="108" android:viewportHeight="108">\n' + g + '</vector>\n')


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for name, paths in GLYPHS.items():
        (OUT / f"ic_{name}.xml").write_text(vector(paths))
    # Notification small icon (white, no tint attr needed but harmless).
    (OUT / "ic_notify.xml").write_text(vector(GLYPHS["mode_nc"]))
    (OUT / "ic_launcher_fg.xml").write_text(adaptive_layer(mark("#FFFFFFFF"), 0.9))
    (OUT / "ic_launcher_mono.xml").write_text(adaptive_layer(mark("#FF000000"), 0.9))
    (OUT / "ic_splash.xml").write_text(adaptive_layer(mark("@color/teal"), 0.9))
    (OUT / "ic_launcher_bg.xml").write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by tools/icons.py -->\n'
        '<shape xmlns:android="http://schemas.android.com/apk/res/android"><solid android:color="#FF00696B"/></shape>\n')
    mip = ROOT / "app/src/main/res/mipmap-anydpi"
    mip.mkdir(parents=True, exist_ok=True)
    (mip / "ic_launcher.xml").write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
        '    <background android:drawable="@drawable/ic_launcher_bg"/>\n    <foreground android:drawable="@drawable/ic_launcher_fg"/>\n'
        '    <monochrome android:drawable="@drawable/ic_launcher_mono"/>\n</adaptive-icon>\n')
    print(len(GLYPHS) + 5, "drawables")


if __name__ == "__main__":
    main()
