#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Draws HearOn Link's icon: rounded headphones with three sound bars between the ear cups, on a soft
scalloped (Material 3 Expressive "cookie") shape over teal. Plain geometry, no fonts. Writes:
  app/src/main/res/drawable/ic_launcher_bg.xml     teal, full bleed, with the scalloped shape
  app/src/main/res/drawable/ic_launcher_fg.xml     headphones + bars (108 dp canvas, inside the 66 dp safe zone)
  app/src/main/res/drawable/ic_launcher_mono.xml   themed icon: the same mark in one tone
  app/src/main/res/drawable/ic_splash.xml          the mark in teal for the splash screen
  app/src/main/res/mipmap-anydpi/ic_launcher.xml   the adaptive icon
  docs/images/icon.svg, docs/images/icon.png       README art (rounded square)
    python3 tools/logo.py [--preview OUT.png]
"""
import math
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
TEAL = "#006A68"
SHAPE = "#0E7F7C"
WHITE = "#FFFFFF"
MINT = "#9EF0E6"
C = 54.0


def f(v):
    return f"{v:.2f}".rstrip("0").rstrip(".")


def cookie(cx, cy, r, lobes=12, amp=0.045, steps=240):
    pts = []
    for i in range(steps):
        a = 2 * math.pi * i / steps
        rr = r * (1 + amp * math.cos(lobes * a))
        pts.append(f"{f(cx + rr * math.sin(a))},{f(cy - rr * math.cos(a))}")
    return "M" + " L".join(pts) + " Z"


def rrect(x, y, w, h, r):
    return (f"M{f(x + r)},{f(y)} h{f(w - 2 * r)} a{f(r)},{f(r)} 0 0 1 {f(r)},{f(r)} v{f(h - 2 * r)} "
            f"a{f(r)},{f(r)} 0 0 1 {f(-r)},{f(r)} h{f(-(w - 2 * r))} a{f(r)},{f(r)} 0 0 1 {f(-r)},{f(-r)} "
            f"v{f(-(h - 2 * r))} a{f(r)},{f(r)} 0 0 1 {f(r)},{f(-r)} Z")


# Headphones on the 108 canvas: band from x 33 to 75, cups 13 wide.
BAND_R = 20.0
BAND_Y = 57.0            # where the band meets the cups
BAND_W = 6.2             # band stroke width
CUP_W, CUP_H, CUP_R = 13.0, 22.0, 6.5
CUP_Y = 53.5
LEFT_X, RIGHT_X = C - BAND_R - CUP_W / 2 - 1.6, C + BAND_R - CUP_W / 2 + 1.6


def band():
    # An open arc (stroke) over the head: from the left cup to the right cup.
    return f"M{f(C - BAND_R)},{f(BAND_Y)} v-1.5 a{f(BAND_R)},{f(BAND_R)} 0 0 1 {f(2 * BAND_R)},0 v1.5"


def cups():
    return rrect(LEFT_X, CUP_Y, CUP_W, CUP_H, CUP_R) + " " + rrect(RIGHT_X, CUP_Y, CUP_W, CUP_H, CUP_R)


def bars():
    # Three sound bars, centred between the cups, tallest in the middle.
    out = []
    for dx, h in ((-7.0, 8.0), (0.0, 14.0), (7.0, 8.0)):
        w = 4.2
        out.append(rrect(C + dx - w / 2, CUP_Y + CUP_H / 2 - h / 2, w, h, w / 2))
    return " ".join(out)


def vector(body, extra=""):
    return ('<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by tools/logo.py -->\n'
            '<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="108dp" android:height="108dp" '
            f'android:viewportWidth="108" android:viewportHeight="108"{extra}>\n{body}</vector>\n')


def vpath(d, fill=None, stroke=None, width=None):
    a = f'android:pathData="{d}"'
    if fill:
        a += f' android:fillColor="{fill}"'
    if stroke:
        a += f' android:strokeColor="{stroke}" android:strokeWidth="{width}" android:strokeLineCap="round" android:fillColor="#00000000"'
    return f"    <path {a}/>\n"


def mark(band_color, cup_color, bar_color):
    return vpath(band(), stroke=band_color, width=BAND_W) + vpath(cups(), fill=cup_color) + vpath(bars(), fill=bar_color)


def svg(size=512, rounded=True, cid="c"):
    clip = f'<clipPath id="{cid}"><rect width="108" height="108" rx="{30 if rounded else 54}"/></clipPath>'
    return (f'<svg xmlns="http://www.w3.org/2000/svg" width="{size}" height="{size}" viewBox="0 0 108 108">{clip}'
            f'<g clip-path="url(#{cid})"><rect width="108" height="108" fill="{TEAL}"/>'
            f'<path d="{cookie(C, C, 36)}" fill="{SHAPE}"/>'
            f'<path d="{band()}" stroke="{WHITE}" stroke-width="{BAND_W}" stroke-linecap="round" fill="none"/>'
            f'<path d="{cups()}" fill="{WHITE}"/><path d="{bars()}" fill="{MINT}"/></g></svg>')


def main():
    res = ROOT / "app/src/main/res/drawable"
    (res / "ic_launcher_bg.xml").write_text(vector(vpath("M0,0h108v108h-108z", fill=TEAL) + vpath(cookie(C, C, 36), fill=SHAPE)))
    (res / "ic_launcher_fg.xml").write_text(vector(mark(WHITE, WHITE, MINT)))
    (res / "ic_launcher_mono.xml").write_text(vector(mark("#FF000000", "#FF000000", "#FF000000")))
    (res / "ic_splash.xml").write_text(vector(mark("@color/teal", "@color/teal", "@color/teal")))
    mip = ROOT / "app/src/main/res/mipmap-anydpi"
    mip.mkdir(parents=True, exist_ok=True)
    (mip / "ic_launcher.xml").write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
        '    <background android:drawable="@drawable/ic_launcher_bg"/>\n    <foreground android:drawable="@drawable/ic_launcher_fg"/>\n'
        '    <monochrome android:drawable="@drawable/ic_launcher_mono"/>\n</adaptive-icon>\n')
    docs = ROOT / "docs/images"
    docs.mkdir(parents=True, exist_ok=True)
    (docs / "icon.svg").write_text(svg())
    subprocess.run(["rsvg-convert", "-w", "512", "-h", "512", str(docs / "icon.svg"), "-o", str(docs / "icon.png")], check=True)
    if "--preview" in sys.argv:
        out = pathlib.Path(sys.argv[sys.argv.index("--preview") + 1])
        from PIL import Image
        parts = []
        for name, rounded in (("circle", False), ("square", True)):
            t = out.with_name(out.stem + f"-{name}.svg"); t.write_text(svg(220, rounded))
            png = t.with_suffix(".png"); subprocess.run(["rsvg-convert", "-w", "220", "-h", "220", str(t), "-o", str(png)], check=True)
            parts.append(Image.open(png).convert("RGBA"))
        small = parts[0].resize((56, 56), Image.LANCZOS)
        im = Image.new("RGBA", (760, 300), (243, 246, 245, 255))
        im.paste((21, 25, 26, 255), (380, 0, 760, 300))
        im.alpha_composite(parts[0], (40, 40)); im.alpha_composite(parts[1], (500, 40))
        im.alpha_composite(small, (290, 120)); im.alpha_composite(small, (410, 120))
        im.save(out); print(out)

if __name__ == "__main__":
    main()
